name = "Origins Season 3 Pack"
author = "John Cena"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87167e927d273c852c5d1e2df1099a26243e9889170f07697173a7015bf1f3e9"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
