name = "Origins Season 3 Pack"
author = "John Cena"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a79d75ad8f418c7382bd6bee7ef23676c41d83adb227660b70034601a67f510e"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
