name = "Origins Season 3 Pack"
author = "John Cena"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47d1298b93fb9f749151ba97019d0428bf04415709eb3c0f163b908d4fc08032"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
