name = "Origins Season 3 Pack"
author = "John Cena"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "859646784bac2cc131ab08172e6b7b72ff487b222bb8780d799e5e3d4bff63f4"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
