name = "Origins Season 3 Pack"
author = "John Cena"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81d8376510b2e4e75e18ee2a66040aa7eea3241d2ca36aa3db2235370579da60"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["curseforge"]
