name = "Origins Season 3 Pack"
author = "John Cena"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f9e3c6c4cd328f54c5fb1a23c68199eeda6461be772bd1e8e4caf8a73826620"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
