name = "Origins Season 3 Pack"
author = "John Cena"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7cafc0029c62ae145b192b756dd11720c3934f905769e64465f89452474846e"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
